// Code generated by MockGen. DO NOT EDIT.
// Source: formvalidator.go

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	usecase "github.com/pwnedgod/tanshogyo/services/product/internal/app/product/usecase"
)

// MockProductFormValidator is a mock of ProductFormValidator interface.
type MockProductFormValidator struct {
	ctrl     *gomock.Controller
	recorder *MockProductFormValidatorMockRecorder
}

// MockProductFormValidatorMockRecorder is the mock recorder for MockProductFormValidator.
type MockProductFormValidatorMockRecorder struct {
	mock *MockProductFormValidator
}

// NewMockProductFormValidator creates a new mock instance.
func NewMockProductFormValidator(ctrl *gomock.Controller) *MockProductFormValidator {
	mock := &MockProductFormValidator{ctrl: ctrl}
	mock.recorder = &MockProductFormValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductFormValidator) EXPECT() *MockProductFormValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockProductFormValidator) Validate(ctx context.Context, form usecase.ProductForm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, form)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockProductFormValidatorMockRecorder) Validate(ctx, form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockProductFormValidator)(nil).Validate), ctx, form)
}
